"""Modified schema to store reviews in efficient manner

Revision ID: 390257624210
Revises: a4d195b3f394
Create Date: 2026-06-01 21:40:50.236093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '390257624210'
down_revision: Union[str, Sequence[str], None] = 'a4d195b3f394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_files', sa.Column('source_type', sa.String(length=16), nullable=False))
    op.add_column('review_issue_details', sa.Column('code_example_blob_path', sa.Text(), nullable=True))
    op.drop_column('review_issue_details', 'code_example')
    op.add_column('review_issues', sa.Column('suggested_fix_blob_path', sa.Text(), nullable=True))
    op.drop_column('review_issues', 'suggested_fix')
    op.add_column('reviews', sa.Column('storage_provider', sa.String(length=32), nullable=False))
    op.add_column('reviews', sa.Column('storage_bucket', sa.String(length=255), nullable=False))
    op.add_column('reviews', sa.Column('input_blob_path', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('input_blob_size', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('input_blob_hash', sa.String(length=128), nullable=True))
    op.add_column('reviews', sa.Column('output_blob_path', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('output_blob_size', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('output_blob_hash', sa.String(length=128), nullable=True))
    op.add_column('reviews', sa.Column('file_count', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('issue_count', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('severity_counts', sa.JSON(), nullable=True))
    op.drop_column('reviews', 'diff_content')
    op.drop_column('reviews', 'result_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('result_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('diff_content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'severity_counts')
    op.drop_column('reviews', 'issue_count')
    op.drop_column('reviews', 'file_count')
    op.drop_column('reviews', 'output_blob_hash')
    op.drop_column('reviews', 'output_blob_size')
    op.drop_column('reviews', 'output_blob_path')
    op.drop_column('reviews', 'input_blob_hash')
    op.drop_column('reviews', 'input_blob_size')
    op.drop_column('reviews', 'input_blob_path')
    op.drop_column('reviews', 'storage_bucket')
    op.drop_column('reviews', 'storage_provider')
    op.add_column('review_issues', sa.Column('suggested_fix', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('review_issues', 'suggested_fix_blob_path')
    op.add_column('review_issue_details', sa.Column('code_example', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('review_issue_details', 'code_example_blob_path')
    op.drop_column('review_files', 'source_type')
    # ### end Alembic commands ###
