"""added guest_token column in reviews table 

Revision ID: a4d195b3f394
Revises: 0fca18c4f37d
Create Date: 2026-05-29 06:42:05.715585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d195b3f394'
down_revision: Union[str, Sequence[str], None] = '0fca18c4f37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('guest_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'reviews', ['guest_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_column('reviews', 'guest_token')
    # ### end Alembic commands ###
