"""Renamed file_path to file_name in review_files

Revision ID: e112947ea3b3
Revises: 55fb721969f1
Create Date: 2026-06-04 06:12:22.347229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e112947ea3b3'
down_revision: Union[str, Sequence[str], None] = '55fb721969f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_files', sa.Column('file_name', sa.Text(), nullable=False))
    op.drop_column('review_files', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_files', sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('review_files', 'file_name')
    # ### end Alembic commands ###
